### ISSUE TITLE
Please upload this project to PyPI

### ISSUE THREAD

**Issue by bslava** [tkrebes/nisyscfg-python#31]
Hello,

Thanks for a very useful project. What do you think about uploading it to [PyPI](https://pypi.org/search/?q=nisyscfg)?

Regards,
Slava

**Comment by tkrebes** [comment]
Hi Slava,

Thank you for your interest in this project. I published an initial version of nisyscfg to [PyPI](https://pypi.org/project/nisyscfg/0.0.1/).

Regards,
-Tyler
