### ISSUE TITLE
nisyscfg resource.is_device query for PXIe-4309 is not working as expected 

### ISSUE THREAD

**Issue by nahumpodokshik** [tkrebes/nisyscfg-python#35]
I use the following code to collect Slot_names, SN , last calibration date and current temperature for PXIe-1092 chassis with 5 mounted PXIe-4309 slots: 
 nisystem_resource = []
    with nisyscfg.Session() as session:
        filter = session.create_filter()
        filter.is_present = True
        filter.is_ni_product = True
        for resource in session.find_hardware(filter):
            if resource.is_device:
                nisystem_resource.append(str(resource.expert_user_alias[0]))
                nisystem_resource.append(str(resource.serial_number))
                #nisystem_resource.append(str(resource.external_calibration_last_time))
                #nisystem_resource.append(str(resource.current_temp))
 print (nisystem_resource)
The query cannot separate 4309 card from TB MT adapter and MXI card. As result resource.current_temp and resource.external_calibration_last_time crashes with exception _nisyscfg.errors.LibraryError: Status.PROP_DOES_NOT_EXIST_: 

output example for the print (nisystem_resource):
['PXI1Slot5', '01D80D59', 'Dev1', '01D73EF9', 'PXI1Slot2', '01D73F07', 'TB-4309 (MT)/PXI1Slot2/0', '01CF4765', 'PXI1Slot3', '01D80D54', 'TB-4309 (MT)/PXI1Slot3/0', '01E60B0B', 'PXI1Slot4', '01D80D5F', 'TB-4309 (MT)/PXI1Slot4/0', '01E60B0C', 'MXI1', '', 'PXIChassis1', '31CFB9B', 'PXI1Slot1', '31C6BB9']

Used nisyscfg is rev 0.0.4

**Comment by nahumpodokshik** [comment]
![image](https://user-images.githubusercontent.com/96178929/148956256-dcf0ffa6-71db-4157-828b-8b3b2e77bc85.png)

I added screenshot for my system with the issue.

**Comment by tkrebes** [comment]
MXI card is considered a device by NI System Configuration so more information is needed to identify the PXIe-4309 devices. Given that all these DAQmx devices are the same, you could filter with product_id. But, I would recommend using expert_name. The following code snippet will give you the name of primary expert:

```python
import nisyscfg
with nisyscfg.Session() as session:
    filter = session.create_filter()
    filter.is_present = True
    filter.is_ni_product = True
    for resource in session.find_hardware(filter):
        print(f'{resource.expert_user_alias[0]}: {resource.expert_name[0]}')
```
It should return "daqmx" as the expert name for the PXIe-4309s. If you set that property on the filter, the code give you the calibration temperatures for these devices:
```python
import nisyscfg
nisystem_resource = []
with nisyscfg.Session() as session:
    filter = session.create_filter()
    filter.is_present = True
    filter.is_ni_product = True
    filter.is_device = True
    filter.expert_name = 'daqmx'
    for resource in session.find_hardware(filter):
        nisystem_resource.append(str(resource.expert_user_alias[0]))
        nisystem_resource.append(str(resource.serial_number))
        nisystem_resource.append(str(resource.external_calibration_last_time))
        nisystem_resource.append(str(resource.current_temp))
print (nisystem_resource)
```

**Comment by tkrebes** [comment]
Depending on you use case, here are a few other option that might work for you.
### Ignore devices not connected to the PCI bus
```python
import nisyscfg
import nisyscfg.enums
nisystem_resource = []
with nisyscfg.Session() as session:
    filter = session.create_filter()
    filter.is_present = True
    filter.is_ni_product = True
    filter.is_device = True
    filter.expert_name = 'daqmx'
    for resource in session.find_hardware(filter):
        if resource.connects_to_bus_type == nisyscfg.enums.BusType.PCI_PXI:
            nisystem_resource.append(str(resource.expert_user_alias[0]))
            nisystem_resource.append(str(resource.serial_number))
            nisystem_resource.append(str(resource.external_calibration_last_time))
            nisystem_resource.append(str(resource.current_temp))

print (nisystem_resource)
```
### Catch the exception and ignore PROP_DOES_NOT_EXIST
```python
import nisyscfg
import nisyscfg.errors
nisystem_resource = []
with nisyscfg.Session() as session:
    filter = session.create_filter()
    filter.is_present = True
    filter.is_ni_product = True
    for resource in session.find_hardware(filter):
        nisystem_resource.append(str(resource.expert_user_alias[0]))
        nisystem_resource.append(str(resource.serial_number))
        try:
            nisystem_resource.append(str(resource.external_calibration_last_time))
            nisystem_resource.append(str(resource.current_temp))
        except nisyscfg.errors.LibraryError as e:
            if e.code != nisyscfg.errors.Status.PROP_DOES_NOT_EXIST:
                raise

print (nisystem_resource)
```
### Use get_property which can default the value if the property does not exist
```python
import nisyscfg
nisystem_resource = []
with nisyscfg.Session() as session:
    filter = session.create_filter()
    filter.is_present = True
    filter.is_ni_product = True
    for resource in session.find_hardware(filter):
        nisystem_resource.append(str(resource.expert_user_alias[0]))
        nisystem_resource.append(str(resource.serial_number))
        nisystem_resource.append(str(resource.get_property("external_calibration_last_time", default=None)))
        nisystem_resource.append(str(resource.get_property("current_temp", default=None)))

print (nisystem_resource)
```

**Comment by nahumpodokshik** [comment]
the filter "if resource.connects_to_bus_type == nisyscfg.enums.BusType.PCI_PXI" doing the job perfectly for our PXIe-4309 and for PXI-628X
['PXI1Slot5', '01D80D59', '2018-09-03 13:22:35', '36.0', 'Dev1', '01D73EF9', '2018-08-21 05:55:29', '36.75', 'PXI1Slot2', '01D73F07', '2018-08-16 13:57:49', '36.5', 'PXI1Slot3', '01D80D54', '2018-08-30 14:37:40', '36.25', 'PXI1Slot4', '01D80D5F', '2018-09-06 15:42:47', '36.0']

What is the **resource** property can be  used to add to my query card model (4309, etc.) ?
Thank you very much for the help!!

**Comment by nahumpodokshik** [comment]
please advice, if possible to read with the **resource**. query PXI cards healthy states (functional/not-functional/active/idle/etc.)?

thanks and best regards!

**Comment by nahumpodokshik** [comment]
i fount the property to read card/chassis model ---> **resource.product_name**.
it is working for me.

thanks and best regards!!

**Comment by tkrebes** [comment]
> please advice, if possible to read with the **resource**. query PXI cards healthy states (functional/not-functional/active/idle/etc.)?
> 
> thanks and best regards!

I don't know if all that information is available via NI System Configuration. If you can find it is NI MAX, it can likely be queried from this API. Lots of the device information found in NI MAX can be accessed via NI System Configuration, but some may come from device specific APIs.

In this Python API, HardwareResource supports running [self_test()](https://github.com/tkrebes/nisyscfg-python/blob/c85d712071e774b0dd2ea18197fe4e22dc051e59/nisyscfg/hardware_resource.py#L296) which might be useful. It also supports, the [Resource](https://github.com/tkrebes/nisyscfg-python/blob/c85d712071e774b0dd2ea18197fe4e22dc051e59/nisyscfg/properties.py#L329) and [IndexedResource](https://github.com/tkrebes/nisyscfg-python/blob/c85d712071e774b0dd2ea18197fe4e22dc051e59/nisyscfg/properties.py#L434) listed in [nisyscfg/properties.py](https://github.com/tkrebes/nisyscfg-python/blob/c85d712071e774b0dd2ea18197fe4e22dc051e59/nisyscfg/properties.py). Properties listed in these two groups are accessed with their lower-case equivalents as properties of the HardwareResource object. The names of the properties should be similar to their LabVIEW counterparts: https://zone.ni.com/reference/en-XX/help/373107N-01/nisyscfg/property_node_hardware/

**Comment by nahumpodokshik** [comment]
I see Status on the NI System Configuration window, but cannot find relevant property when use the following query 
![image](https://user-images.githubusercontent.com/96178929/149665586-faf22100-93b6-48f0-8c40-cdd87df6553d.png)

            if resource.expert_name[0] == "daqmx": #just as example
                if resource.connects_to_bus_type == nisyscfg.enums.BusType.PCI_PXI:

**Comment by tkrebes** [comment]
The Status property is a special case for NI MAX and is the combination of IsPresent and IsSimulated. Below is the Python equivalent of how NI MAX implements Status. (Note: The NI GPIB-ENET/1000 has a slightly different implementation.)

```python
import nisyscfg.enums
import nisyscfg.hardware_resource

def get_status(resource: nisyscfg.hardware_resource.HardwareResource) -> str:
    """Returns the status of the target"""
    if resource.is_simulated:
        return "Simulated"
    return {
        nisyscfg.enums.IsPresentType.PRESENT: "Present",
        nisyscfg.enums.IsPresentType.NOT_PRESENT: "Not Present",
        nisyscfg.enums.IsPresentType.INITIALIZING: "Initializing",
    }.get(resource.is_present, "Unknown")
```
If you are not working with simulated devices, you can just query resource.is_present.

**Comment by nahumpodokshik** [comment]
Thanks for the suggestion and the example! This works well for me.

thanks and best regards!

**Comment by nahumpodokshik** [comment]
please advice how to use the same python API to query and to collect version of installed NI-DAQmx Device Driver? 

thanks!

**Comment by nahumpodokshik** [comment]
i will open "new issue" for my last questions.
Case for PXIe-4309 is solved and the solution works properly for me. Thanks and best regards!!!
