### ISSUE TITLE
[question] how to change the network settings from a remote target?

### ISSUE THREAD

**Issue by rscd27p** [tkrebes/nisyscfg-python#37]
Hi tkrebes, thanks for all the work you have put into this. I am writing a simple function to get the network configuration of a remote target. The code I have is:

The target is a cRIO-9049 and I am running the code on a Windows 10 machine. My function looks like this: 

```python
def get_network_settings(target_name: str,username: str,password: str):
    nisystem_resource = {}
    print("Trying to connect to target: " + target_name)
    with nisyscfg.Session(target=target_name,username=username,password=password) as session: 
        print("Succesfully connected to target: " + str(session.resource.name))
        print("session.resource dir: " + str(dir(session.resource)) + "\n\n")
        nisystem_resource['serial_number'] = str(session.resource.serial_number)
        nisystem_resource['tcp_ip_v4_address'] = str(session.resource.tcp_ip_v4_address)
        nisystem_resource['tcp_ip_v4_subnet'] = str(session.resource.tcp_ip_v4_subnet)
        nisystem_resource['tcp_ip_v4_gateway'] = str(session.resource.tcp_ip_v4_gateway)
        nisystem_resource['tcp_ip_v4_dns_server'] = str(session.resource.tcp_ip_v4_dns_server)
        print(nisystem_resource)
        print("Closing Session")
        session.close()
```

It seems that I am having trouble accessing the properties of the hardware resource, I also tried using this 
 format **session.resource.get_property()**
 
 However, in both cases, I got this error:  **Status.PROP_DOES_NOT_EXIST**

I wanted to read the properties first and after being successful I wanted to try to modify them. Ia m referencing the properties here: [Properties.py](https://github.com/tkrebes/nisyscfg-python/blob/c85d712071e774b0dd2ea18197fe4e22dc051e59/nisyscfg/properties.py#L329)
 
Am I doing something wrong? Thanks in advance for your help.

**Comment by tkrebes** [comment]
I assume the question has been answered.
