### ISSUE TITLE
authorship question

### ISSUE THREAD

**Issue by franzhaas** [tkrebes/nisyscfg-python#39]
Dear Tyler Krehbiel,

as author in setup.py national instruments is stated. is this correct? A ni email address is given as your email maintainer address but the project is not hosted on the official ni GitHub page. (https://github.com/ni)

Can you give some background on authorship/ownership of the code?

Thanks in advance,
Franz

**Comment by franzhaas** [comment]
(technically a question not a bug, but i messed up and got the bug label on it, now i cant get rid of it... sry...)

**Comment by tkrebes** [comment]
Hi,

This Python project is one of the NI System Configuration Python APIs that we use internally at NI. It is used in both automated test and production code. My intent has been to move the project to NI’s GitHub page. In recent years, NI has been improving its support for open-source projects hosted on GitHub. I have maintained the project in my personal space until a clean handoff can be established.

-Tyler

**Comment by tkrebes** [comment]
I assume the question has been answered.
