### ISSUE TITLE
session.get_installed_software_components() output format

### ISSUE THREAD

**Issue by nahumpodokshik** [tkrebes/nisyscfg-python#42]
**Describe the bug**
Hello,

i am using NISYSCFG 0.0.4 release in the following python script to collect info for installed NI SW:
**import nisyscfg
host="localhost"
with nisyscfg.Session(target=host) as session:
    for component in session.get_installed_software_components():
        print(component.title, component.version)**

component.version return string some HEX data (for example  -0+f138). See below the collected example.
how to filter this unused HEX data?

thanks,
Nahum

ASAM e.V. DataPlugin for AOP5 21.5.0.49290-0+f138
ASAM e.V. DataPlugin for AOP6 21.5.0.49290-0+f138
ASAM e.V. DataPlugin for MDF4 21.5.0.49291-0+f139
DIAdem English 22.0.0.49381-0+f229
FlexLogger 22.2.0.49213-0+f61
LabVIEW Runtime (32-bit) 19.1.4.49152-0+f0
LabVIEW Runtime (32-bit) 20.1.0.49152-0+f0
LabVIEW Runtime (32-bit) 21.1.0.49476-0+f324
LabVIEW Runtime (64-bit) 16.6.7.49153-0+f1
LabVIEW Runtime (64-bit) 20.1.0.49152-0+f0
LabVIEW Runtime (64-bit) 21.1.0.49476-0+f324
LabWindows/CVI Analysis Library Runtime 20.0.0.49152-0+f0
LabWindows/CVI DotNet 17.0.0.49155-0+f3
LabWindows/CVI Low-Level Driver 17.5.0.49152-0+f0
LabWindows/CVI Network Streams 17.0.0.49155-0+f3
LabWindows/CVI Network Variable 17.0.0.49155-0+f3
LabWindows/CVI Shared Runtime 2017 17.0.0.49157-0+f5
LabWindows/CVI Shared Runtime 2017 Merge Module Redeployment Support 17.0.0.49155-0+f3
LabWindows/CVI TDMS 17.0.0.49155-0+f3
Microsoft/IBM DataPlugin for Audio 21.5.0.49291-0+f139
NI 1588-2008 Network Management Runtime 18.1.0 18.10.24
NI Certificates Installer 21.5.0.49170-0+f18
NI Device Monitor 21.0.0.49152-0+f0
NI Hardware Configuration Importer 8.4.0.49152-0+f0
NI Help Viewer File Package 19.0.1.49152-0+f0
NI I/O Trace 21.5.0.49393-0+f241
NI LabVIEW 2016 Runtime 16.5.1.49152-0+f0
NI LabVIEW 2017 Runtime 17.5.1.49152-0+f0
NI License Manager 21.8.0.49275-0+f123
NI Linux RT System Image 21.0.0.49309-0+f157
NI Linux RT System Image 21.5.0.49335-0+f183
NI Measurement & Automation Explorer 21.5.0.49391-0+f239
NI Package Manager 21.8.0.49275-0+f123
NI System Configuration .NET Runtime 21.5.0.49392-0+f240
NI System Configuration Runtime 21.5.0.49392-0+f240
NI System Configuration support for LabWindows/CVI 18.5.0.49153-0+f1
NI System Web Server 2019 19.0.0.49152-0+f0
NI SystemLink Alarm and Notification Web UI 21.5.0.49361-0+f209
NI SystemLink Message Client Runtime 21.5.0.49348-0+f196
NI SystemLink Tag Client Runtime 21.5.0.49348-0+f196
NI SystemLink Tag Service Web UI 21.5.0.49361-0+f209
NI Update Service 21.0.0.49243-0+f91
NI USI Core 21.5.0.49152-0+f0
NI Web Server 21.3.0.49152-0+f0
NI-488.2 18.5.0.49153-0+f1
NI-488.2 C/C++ Support 18.5.0.49152-0+f0
NI-488.2 DLL Direct Entry Support 18.5.0.49152-0+f0
NI-488.2 Documentation 18.5.0.49152-0+f0
NI-488.2 LabWindows/CVI Support 18.5.0.49152-0+f0
NI-488.2 MAX Support 18.5.0.49152-0+f0
NI-488.2 Runtime 18.5.0.49152-0+f0
NI-488.2 Utilities 18.5.0.49152-0+f0
NI-488.2 Visual Basic Support 18.5.0.49152-0+f0
NI-DAQmx 21.3.0.49319-0+f167
NI-DAQmx .NET Language Runtime for .NET Framework 4.0 21.0.0.49316-0+f164
NI-DAQmx .NET Language Runtime for .NET Framework 4.0 21.3.0.49317-0+f165
NI-DAQmx .NET Language Runtime for .NET Framework 4.5 21.0.0.49316-0+f164
NI-DAQmx .NET Language Runtime for .NET Framework 4.5 21.3.0.49317-0+f165
NI-DAQmx cDAQ Firmware 21.3.0.49310-0+f158
NI-DAQmx Runtime 21.3.0.49317-0+f165
NI-DAQmx Runtime with Configuration Support 21.3.0.49319-0+f167
NI-DAQmx Support for .NET Framework 4.0 Languages 21.3.0.49319-0+f167
NI-DAQmx Support for .NET Framework 4.5 Languages 21.3.0.49319-0+f167
NI-DAQmx Support for C 21.3.0.49319-0+f167
NI-VISA 18.5.0.49152-0+f0
NI-VISA .NET Development Support 17.5 17.5.0.49152-0+f0
NI-VISA .NET Runtime 17.5 17.5.0.49152-0+f0
NI-VISA C Examples 18.5.0.49152-0+f0
NI-VISA Configuration Support 21.5.0.49252-0+f100
NI-VISA Driver Development Wizard 18.5.0.49152-0+f0
NI-VISA Interactive Control 21.5.0.49252-0+f100
NI-VISA Runtime 21.5.0.49252-0+f100
NI-VISA Server 21.5.0.49252-0+f100
NI-XNET 21.5.0.49342-0+f190
NI-XNET Database Editor 21.5.0.49342-0+f190
NI-XNET Runtime 21.5.0.49340-0+f188
NI-XNET Support for Microsoft Visual C/C++ 21.5.0.49340-0+f188
NI-XNET Utilities 21.5.0.49340-0+f188
PACS v4.3 1.0.13
PXI Platform Services 21.5.0.49272-0+f120
PXI Platform Services Configuration 21.5.0.49271-0+f119
PXI Platform Services Runtime 21.5.0.49271-0+f119
PXI Platform Services Support for .NET 21.5.0.49271-0+f119
PXI Platform Services Support for Visual C 21.5.0.49271-0+f119
TDM Excel Add-In 21.5.0.49361-0+f209
Variable Engine 21.0.0.49350-0+f198

**To Reproduce**
1. install nisyscfg PY module
2. run the code
3. check the component.version output 
4. See HEX values

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by marcoskirsch** [comment]
Hello, the `0+f138` is not an incorrectly appended hexadecimal number. It's the build number for the product.=, e.g. "final 138". It's correct, albeit – I agree – ugly.

**Comment by nahumpodokshik** [comment]
hello,

thanks for the clarification
