### ISSUE TITLE
resource.external_calibration_last_time and resource.current_temp not works for PXI-4309 card

### ISSUE THREAD

**Issue by nahumpodokshik** [tkrebes/nisyscfg-python#43]
**Describe the bug**
resource.external_calibration_last_time and resource.current_temp not works for PXI-4309 card and provide exception
**nisyscfg.errors.LibraryError: Status.PROP_DOES_NOT_EXIST:**
****Error: return self._type_property.get(instance._property_accessor)**** 
As I remember, it was functional for one of previous 
**To Reproduce**
1. install NIDAQmx device driver and MAX Config 22.5
2. install nisyscfg 0.0.5 release
3. connect chassis with installed PXIe-4309 and chassis with PXI-6284
4. run the following: 
    nisystem_resource = []
    with nisyscfg.Session() as session:
        filter = session.create_filter()
        filter.is_present = True
        filter.is_ni_product = True
        for resource in session.find_hardware(filter):
            if resource.is_device:
                nisystem_resource.append(str(resource.expert_user_alias[0]))
                nisystem_resource.append(str(resource.serial_number))
                nisystem_resource.append(str(resource.external_calibration_last_time))
                nisystem_resource.append(str(resource.current_temp))
            if resource.is_chassis:
                nisystem_resource.append(str(resource.expert_user_alias[0]))
                pass
        return nisystem_resource

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/96178929/198881682-653795ec-4141-494c-b686-5bad1eadc0ab.png)

**Desktop (please complete the following information):**
 - Win 10

**Additional context**

**Comment by tkrebes** [comment]
Hi,

I tested out the sample code provided above. I have a few ideas on what might be happening. I was able to test it with a PXIe-4309, but I did not have a PXI-6284 on hand. I think it is likely that the PXI-6284 does not support the `external_calibration_last_time` property. And I suspect, the exception is occurring on that resource instead of the PXIe-4309. 

I would recommend trying the following things:

1. Check the property in `NI MAX`. For example,
![image](https://user-images.githubusercontent.com/39509337/199062780-4e83bd77-4e03-486d-96a1-4fe4010e62e4.png)

2. Try the following code:
```python
import nisyscfg
with nisyscfg.Session() as session:
    filter = session.create_filter()
    filter.is_present = True
    filter.is_ni_product = True
    for resource in session.find_hardware(filter):
        print(f'{resource.product_name} "{resource.expert_user_alias[0]}"')
        print(f"   Settings")
        print(f"      Name                       {resource.expert_user_alias[0]}")
        print(f"      Vendor                     {resource.vendor_name}")
        print(f"      Model                      {resource.product_name}")
        print(f"      Serial Number              {resource.serial_number}")
        current_temp = resource.get_property("current_temp", None)
        if current_temp is not None:
            print(f"      Current Device Temperature {resource.current_temp:0.1f}")
        external_calibration_last_time = resource.get_property("external_calibration_last_time", None)
        if external_calibration_last_time is not None:
            print(f"   External Calibration")
            print(f"      Calibration Date           {external_calibration_last_time}")
```
This will produce a report similar to NI MAX. I expect that you'll see `Calibration Date` listed for PXIe-4309 but not the PXI-6284. Also, find_hardware might be returning some other device that does the `external_calibration_last_time` property.

Let me know if `Calibration Date` does not show up for the PXIe-4309.

I hope this helps,
-Tyler

**Comment by nahumpodokshik** [comment]
Hi Tyler,

Thanks for the quick response!!

I tested the suggested code. Please, see below the output of the script in pic#2. For a reminder of what my NI system looks like, see pic#1.

Bingo 😊- the code returned Current Device Temperature and External Calib Date for both models – PXI-6284 and PXIe-4309.
Bad news – the example crashed with exception. It looks like, it happened because of the installed TBT PXIe-8301 module? Right? Sequence of the scanning is not clear for me.  PXIe-8301 is on PXISlot1. Why it is not crashed from beginning?

How to fix this script to have on the resulted output PXIe-8301 with basic data (Model/Serial Number/Orderable Part Number)

Thanks and best regards,
Nahum


Pic#1
***@***.***
Pic#2
*** Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32. ***
*** Remote Python engine is active ***
>>>
*** Remote Interpreter Reinitialized  ***
NI PXIe-4309 "PXI1Slot2"
   Settings
      Name                       PXI1Slot2
      Vendor                     National Instruments
      Model                      NI PXIe-4309
      Serial Number              01FE2661
      Current Device Temperature 30.2
   External Calibration
      Calibration Date           2021-09-09 05:06:13
NI PXIe-4309 "PXI1Slot3"
   Settings
      Name                       PXI1Slot3
      Vendor                     National Instruments
      Model                      NI PXIe-4309
      Serial Number              01F05BFF
      Current Device Temperature 29.5
   External Calibration
      Calibration Date           2020-07-27 07:01:29
NI PXIe-4309 "PXI1Slot4"
   Settings
      Name                       PXI1Slot4
      Vendor                     National Instruments
      Model                      NI PXIe-4309
      Serial Number              01FCF84E
      Current Device Temperature 29.8
   External Calibration
      Calibration Date           2021-09-21 18:33:16
NI PXIe-4309 "PXI1Slot6"
   Settings
      Name                       PXI1Slot6
      Vendor                     National Instruments
      Model                      NI PXIe-4309
      Serial Number              01FDA832
      Current Device Temperature 30.5
   External Calibration
      Calibration Date           2021-09-21 13:55:52
NI PXI-6284 "PXI1Slot7"
   Settings
      Name                       PXI1Slot7
      Vendor                     National Instruments
      Model                      NI PXI-6284
      Serial Number              019EE39F
      Current Device Temperature 24.6
   External Calibration
      Calibration Date           2018-12-11 20:51:30
NI PXIe-4309 "PXI1Slot5"
   Settings
      Name                       PXI1Slot5
      Vendor                     National Instruments
      Model                      NI PXIe-4309
      Serial Number              01D80D54
      Current Device Temperature 30.5
   External Calibration
      Calibration Date           2018-08-30 14:37:40
NI TB-4309 (ST) "TB-4309 (ST)/PXI1Slot4/0"
   Settings
      Name                       TB-4309 (ST)/PXI1Slot4/0
      Vendor                     National Instruments
      Model                      NI TB-4309 (ST)
      Serial Number              01F722F5
NI PXIe-1092 "PXIChassis1"
   Settings
      Name                       PXIChassis1
      Vendor                     National Instruments
      Model                      NI PXIe-1092
      Serial Number              322DEA6
      Current Device Temperature 22.0
   External Calibration
      Calibration Date           2021-09-30 16:35:21
Traceback (most recent call last):
  File "<module1>", line 7, in <module>
  File "C:\Python38\lib\site-packages\nisyscfg\properties.py", line 568, in __get__
    return self._type_property.get(instance._property_accessor)
  File "C:\Python38\lib\site-packages\nisyscfg\properties.py", line 173, in get
    return accessor.get_string_property(self._id)
  File "C:\Python38\lib\site-packages\nisyscfg\properties.py", line 69, in get_string_property
    return self._getter(id, ctypes.c_char_p)
  File "C:\Python38\lib\site-packages\nisyscfg\hardware_resource.py", line 149, in _get_property
    nisyscfg.errors.handle_error(self, error_code)
  File "C:\Python38\lib\site-packages\nisyscfg\errors.py", line 85, in handle_error
    raise LibraryError(status, description)
nisyscfg.errors.LibraryError: Status.PROP_DOES_NOT_EXIST:
>>>

**Comment by tkrebes** [comment]
I suspect the PXIe-8301 does not support the `expert_user_alias[0]` property. However, I did not have the opportunity to test this theory. I am considering adding `has_property()` to the HardwareResource class in PR #47. Below is an example of the code that leverages this new method and should work with the PXIe-8301 assuming my theory is correct.
```python
import nisyscfg
with nisyscfg.Session() as session:
    filter = session.create_filter()
    filter.is_present = True
    filter.is_ni_product = True
    for resource in session.find_hardware(filter):
        print(f'{resource.product_name} "{resource.name}"')
        print(f"   Settings")
        if resource.has_property("expert_user_alias", index=0):
            print(f"      Name                       {resource.expert_user_alias[0]}")
        print(f"      Vendor                     {resource.vendor_name}")
        print(f"      Model                      {resource.product_name}")
        print(f"      Serial Number              {resource.serial_number}")
        if resource.has_property("current_temp"):
            print(f"      Current Device Temperature {resource.current_temp:0.1f}")
        if resource.has_property("external_calibration_last_time"):
            print(f"   External Calibration")
            print(f"      Calibration Date           {resource.external_calibration_last_time}")
```
If you would like to try it out, there is a prebuilt wheel under the Artifacts section on https://github.com/tkrebes/nisyscfg-python/actions/runs/3374456755.

For `Orderable Part Number` property, is this something that you need? I know some drivers report it in NI MAX. Though, it is not currently part of the NI System Configuration API. And in my experience, few drivers implement this property. If you need it, I will see what can be done.

**Comment by nahumpodokshik** [comment]
I don’t see has_property() under the HardwareResource class. Do I need to install a special rev of nisyscfg to get this property supported?

Thanks and bets regards,
Nahum

Pic#1
***@***.*** ***@***.***

**Comment by nahumpodokshik** [comment]
Oh, I see the changes on HardwareResource class in PR #47<https://github.com/tkrebes/nisyscfg-python/pull/47>.

I will try and will update.

Thanks!
Nahum

From: Podokshik, Nahum
Sent: Wednesday, November 02, 2022 09:04
To: tkrebes/nisyscfg-python ***@***.***>; tkrebes/nisyscfg-python ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [tkrebes/nisyscfg-python] resource.external_calibration_last_time and resource.current_temp not works for PXI-4309 card (Issue #43)

I don’t see has_property() under the HardwareResource class. Do I need to install a special rev of nisyscfg to get this property supported?

Thanks and bets regards,
Nahum

Pic#1
***@***.******@***.***

**Comment by nahumpodokshik** [comment]
Hi Tyler,

I updated hardware_resource.py content according to the HardwareResource class in PR #47<https://github.com/tkrebes/nisyscfg-python/pull/47>
Please, See below the output with exception. Looks like properties.py needs some polish.

Thanks,
Nahum



>>>
*** Remote Interpreter Reinitialized  ***
NI PXIe-4309 "PXI1Slot2"
   Settings
      Name                       PXI1Slot2
      Vendor                     National Instruments
      Model                      NI PXIe-4309
      Serial Number              01FE2661
      Current Device Temperature 30.5
   External Calibration
      Calibration Date           2021-09-09 05:06:13
NI PXIe-4309 "PXI1Slot3"
   Settings
      Name                       PXI1Slot3
      Vendor                     National Instruments
      Model                      NI PXIe-4309
      Serial Number              01F05BFF
      Current Device Temperature 29.8
   External Calibration
      Calibration Date           2020-07-27 07:01:29
NI PXIe-4309 "PXI1Slot4"
   Settings
      Name                       PXI1Slot4
      Vendor                     National Instruments
      Model                      NI PXIe-4309
      Serial Number              01FCF84E
      Current Device Temperature 30.0
   External Calibration
      Calibration Date           2021-09-21 18:33:16
NI PXIe-4309 "PXI1Slot6"
   Settings
      Name                       PXI1Slot6
      Vendor                     National Instruments
      Model                      NI PXIe-4309
      Serial Number              01FDA832
      Current Device Temperature 30.8
   External Calibration
      Calibration Date           2021-09-21 13:55:52
NI PXI-6284 "PXI1Slot7"
   Settings
      Name                       PXI1Slot7
      Vendor                     National Instruments
      Model                      NI PXI-6284
      Serial Number              019EE39F
      Current Device Temperature 24.8
   External Calibration
      Calibration Date           2018-12-11 20:51:30
NI PXIe-4309 "PXI1Slot5"
   Settings
      Name                       PXI1Slot5
      Vendor                     National Instruments
      Model                      NI PXIe-4309
      Serial Number              01D80D54
      Current Device Temperature 30.5
   External Calibration
      Calibration Date           2018-08-30 14:37:40
NI TB-4309 (ST) "TB-4309 (ST)/PXI1Slot4/0"
   Settings
      Name                       TB-4309 (ST)/PXI1Slot4/0
      Vendor                     National Instruments
      Model                      NI TB-4309 (ST)
      Serial Number              01F722F5
NI PXIe-1092 "PXIChassis1"
   Settings
      Name                       PXIChassis1
      Vendor                     National Instruments
      Model                      NI PXIe-1092
      Serial Number              322DEA6
      Current Device Temperature 22.0
   External Calibration
      Calibration Date           2021-09-30 16:35:21
Traceback (most recent call last):
  File "<module2>", line 7, in <module>
  File "C:\Python38\lib\site-packages\nisyscfg\properties.py", line 568, in __get__
    return self._type_property.get(instance._property_accessor)
  File "C:\Python38\lib\site-packages\nisyscfg\properties.py", line 173, in get
    return accessor.get_string_property(self._id)
  File "C:\Python38\lib\site-packages\nisyscfg\properties.py", line 69, in get_string_property
    return self._getter(id, ctypes.c_char_p)
  File "C:\Python38\lib\site-packages\nisyscfg\hardware_resource.py", line 151, in _get_property
    nisyscfg.errors.handle_error(self, error_code)
  File "C:\Python38\lib\site-packages\nisyscfg\errors.py", line 85, in handle_error
    raise LibraryError(status, description)
nisyscfg.errors.LibraryError: Status.PROP_DOES_NOT_EXIST:

From: Podokshik, Nahum
Sent: Wednesday, November 02, 2022 09:20
To: tkrebes/nisyscfg-python ***@***.***>; tkrebes/nisyscfg-python ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [tkrebes/nisyscfg-python] resource.external_calibration_last_time and resource.current_temp not works for PXI-4309 card (Issue #43)

Oh, I see the changes on HardwareResource class in PR #47<https://github.com/tkrebes/nisyscfg-python/pull/47>.

I will try and will update.

Thanks!
Nahum

From: Podokshik, Nahum
Sent: Wednesday, November 02, 2022 09:04
To: tkrebes/nisyscfg-python ***@***.******@***.***>>; tkrebes/nisyscfg-python ***@***.******@***.***>>
Cc: Author ***@***.******@***.***>>
Subject: RE: [tkrebes/nisyscfg-python] resource.external_calibration_last_time and resource.current_temp not works for PXI-4309 card (Issue #43)

I don’t see has_property() under the HardwareResource class. Do I need to install a special rev of nisyscfg to get this property supported?

Thanks and bets regards,
Nahum

Pic#1
***@***.******@***.***

**Comment by nahumpodokshik** [comment]
hi TyIer,
I see my screenshot is not on received properly.
![image](https://user-images.githubusercontent.com/96178929/199489080-c3335625-e872-4b0f-b223-e8dcbd41da43.png)
added NIMAX HW configuration

**Comment by nahumpodokshik** [comment]
after discussion, i understand "Orderable Part Number" is equal for all PXIe-8301. i dont need this parameter.

thanks

**Comment by nahumpodokshik** [comment]
**i try to run the fixed HardwareResource class from the GitHub**

**my script:**
import nisyscfg
with nisyscfg.Session() as session:
    filter = session.create_filter()
    filter.is_present = True
    filter.is_ni_product = True
    for resource in session.find_hardware(filter):
        print(f"   Settings")
        print(f"   Resource is present / is device / is ni product = {resource.is_present} / {resource.is_device} / {resource.is_ni_product}")
        if resource.has_property("expert_user_alias", index=0):
            print(f"      Name                       {resource.expert_user_alias[0]}")
        print(f"      Vendor                     {resource.vendor_name}")
        print(f"      Model                      {resource.product_name}")
        print(f"      Serial Number              {resource.serial_number}")
        if resource.has_property("current_temp"):
            print(f"      Current Device Temperature {resource.current_temp:0.1f}")
        if resource.has_property("external_calibration_last_time"):
            print(f"   External Calibration")
            print(f"      Calibration Date           {resource.external_calibration_last_time}")

**and receiving the exception, see below. it is trying to query second time at chassis, but resource.is_device response with Fail **
 *** Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32. ***
>>> 
*** Remote Interpreter Reinitialized  ***
   Settings
   Resource is present / is device / is ni product = 1 / 1 / 1
      Name                       PXI1Slot2
      Vendor                     National Instruments
      Model                      NI PXIe-4309
      Serial Number              01FE2661
      Current Device Temperature 30.2
   External Calibration
      Calibration Date           2021-09-09 05:06:13
   Settings
   Resource is present / is device / is ni product = 1 / 1 / 1
      Name                       PXI1Slot3
      Vendor                     National Instruments
      Model                      NI PXIe-4309
      Serial Number              01F05BFF
      Current Device Temperature 29.8
   External Calibration
      Calibration Date           2020-07-27 07:01:29
   Settings
   Resource is present / is device / is ni product = 1 / 1 / 1
      Name                       PXI1Slot4
      Vendor                     National Instruments
      Model                      NI PXIe-4309
      Serial Number              01FCF84E
      Current Device Temperature 29.8
   External Calibration
      Calibration Date           2021-09-21 18:33:16
   Settings
   Resource is present / is device / is ni product = 1 / 1 / 1
      Name                       PXI1Slot6
      Vendor                     National Instruments
      Model                      NI PXIe-4309
      Serial Number              01FDA832
      Current Device Temperature 30.8
   External Calibration
      Calibration Date           2021-09-21 13:55:52
   Settings
   Resource is present / is device / is ni product = 1 / 1 / 1
      Name                       PXI1Slot7
      Vendor                     National Instruments
      Model                      NI PXI-6284
      Serial Number              019EE39F
      Current Device Temperature 24.8
   External Calibration
      Calibration Date           2018-12-11 20:51:30
   Settings
   Resource is present / is device / is ni product = 1 / 1 / 1
      Name                       PXI1Slot5
      Vendor                     National Instruments
      Model                      NI PXIe-4309
      Serial Number              01D80D54
      Current Device Temperature 30.2
   External Calibration
      Calibration Date           2018-08-30 14:37:40
   Settings
   Resource is present / is device / is ni product = 1 / 1 / 1
      Name                       TB-4309 (ST)/PXI1Slot4/0
      Vendor                     National Instruments
      Model                      NI TB-4309 (ST)
      Serial Number              01F722F5
   Settings
   Resource is present / is device / is ni product = 1 / 1 / 1
      Name                       PXIChassis1
      Vendor                     National Instruments
      Model                      NI PXIe-1092
      Serial Number              322DEA6
      Current Device Temperature 22.0
   External Calibration
      Calibration Date           2021-09-30 16:35:21
   Settings
   Resource is present / is device / is ni product = 1 / 0 / 1
      Name                       PXIChassis1
Traceback (most recent call last):
  File "C:\SVSHARE\NI\module2.py", line 11, in <module>
    print(f"      Vendor                     {resource.vendor_name}")
  File "C:\Python38\lib\site-packages\nisyscfg\properties.py", line 568, in __get__
    return self._type_property.get(instance._property_accessor)
  File "C:\Python38\lib\site-packages\nisyscfg\properties.py", line 173, in get
    return accessor.get_string_property(self._id)
  File "C:\Python38\lib\site-packages\nisyscfg\properties.py", line 69, in get_string_property
    return self._getter(id, ctypes.c_char_p)
  File "C:\Python38\lib\site-packages\nisyscfg\hardware_resource.py", line 151, in _get_property
    nisyscfg.errors.handle_error(self, error_code)
  File "C:\Python38\lib\site-packages\nisyscfg\errors.py", line 85, in handle_error
    raise LibraryError(status, description)
nisyscfg.errors.LibraryError: Status.PROP_DOES_NOT_EXIST:
>>>

**Comment by nahumpodokshik** [comment]
![image](https://user-images.githubusercontent.com/96178929/199500953-026e4db1-41ba-454e-b4a1-1997903be8b6.png)

**Comment by tkrebes** [comment]
I got a change to look at a system with a PXIe-8301 and a PXIe-109x chassis. I found that find_hardware() returns resources that are not classified as a device or chassis. These resources are not required to support properties like vendor name or product name. I would recommend ignoring resources that are not a device or chassis. The following sample code worked for me on that system.
```python
import nisyscfg
with nisyscfg.Session() as session:
    filter = session.create_filter()
    filter.is_present = True
    filter.is_ni_product = True
    for resource in session.find_hardware(filter):
        if not (resource.is_device or resource.is_chassis):
            continue
        print(f'{resource.product_name} "{resource.expert_user_alias[0]}"')
        print(f"   Settings")
        print(f"      Name                       {resource.expert_user_alias[0]}")
        print(f"      Vendor                     {resource.vendor_name}")
        print(f"      Model                      {resource.product_name}")
        print(f"      Serial Number              {resource.serial_number}")
        current_temp = resource.get_property("current_temp", None)
        if current_temp is not None:
            print(f"      Current Device Temperature {resource.current_temp:0.1f}")
        external_calibration_last_time = resource.get_property("external_calibration_last_time", None)
        if external_calibration_last_time is not None:
            print(f"   External Calibration")
            print(f"      Calibration Date           {external_calibration_last_time}")

```

**Comment by nahumpodokshik** [comment]
Thank you!

It is working for my NI systems.

Best regards,
Nahum
