### ISSUE TITLE
Self-Calibrate

### ISSUE THREAD

**Issue by ni-jfitzger** [tkrebes/nisyscfg-python#53]
**Is your feature request related to a problem? Please describe.**
This API looks pretty awesome, but the self_calibrate function appears to be missing.

It's available in the LabVIEW API for hardware resources, but I don't see it anywhere in this API.

**Comment by tkrebes** [comment]
Thanks for the complement. I created PR #54 with a potential implementation. I'm out on vacation and do not have the means to test the change at the moment. But, if the change works for you, I can complete the PR and publish a new package on pypi.org.

Regards,
-Tyler

**Comment by ni-jfitzger** [comment]
It worked for me. Flake8 seems to want a blank line at the end of the file.

Thanks,

[https://www.ni.com/content/dam/web/scene7/email/signature/email-sig-logo.png]
Jay Fitzgerald
Staff Software Engineer
Modular Instruments & Vision Driver Ownership - External
ni.com<https://www.ni.com/>
[https://www.ni.com/content/dam/web/scene7/email/signature/email-sig-banner.png]<https://www.ni.com/r/zf03uz>





INTERNAL - NI CONFIDENTIAL

**Comment by tkrebes** [comment]
Closing, #54 has been merged into main.
